GET http://localhost:3000/users

###
POST http://localhost:3000/add-users
Content-Type: application/json

{
    "name": "user",
    "email": "user@gmail.com",
    "password": "user123",
    "noHP": "00123220198",
    "role": "user"
}

###
GET http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "Joni",
    "email": "jo@gmail.com",
}

###
PUT http://localhost:3000/user/2
Content-Type: application/json

{
    "name": "Jonathan",
    "email": "jonathan@gmail.com",
}

###
DELETE http://localhost:3000/user/2


###
# Create Order
POST http://localhost:3000/add-order
Content-Type: application/json

{
    "user_id": 1,
    "weight": 2,
    "total_price": 25000
}


###
POST http://localhost:3000/add-payment
Content-Type: application/json

{
    "order_id": "1",
    "method": "Cash",
    "amount": "20000",
    "status": "1"
}

###
POST http://localhost:3000/add-users
Content-Type: application/json

{
    "name": "Rio",
    "email": "aryamuktisatria@gmail.com",
    "password": "iniPassSaya2",
    "noHP": "00123220198",
    "role": "customer"
}

###
POST http://localhost:3000/add-users
Content-Type: application/json
{
  "name": "Admin",
  "email": "admin@laundry.com",
  "password": "password123",
  "noHP": "08123456789",
  "role": "admin"
}
###