GET http://localhost:3000/users

###
GET http://localhost:3000/payments/

###
POST http://localhost:3000/add-users
Content-Type: application/json

{
    "name": "RyanKNy",
    "email": "admin3@gmail.com",
    "password": "tccbabik",
    "noHP": "00123220198",
    "role": "admin"
}

###
GET http://localhost:3000/users/1
Content-Type: application/json

{
    "name": "Joni",
    "email": "jo@gmail.com",
}

###
PUT http://localhost:3000/user/2
Content-Type: application/json

{
    "name": "Jonathan",
    "email": "jonathan@gmail.com",
}

###
DELETE http://localhost:3000/user/2


###
# Create Order
POST http://localhost:3000/add-order
Content-Type: application/json

{
    "user_id": 1,
    "weight": 2,
    "total_price": 25000
}


###
POST http://localhost:3000/add-payment
Content-Type: application/json

{
    "order_id": "1",
    "method": "Cash",
    "amount": "20000",
    "status": "1"
}

###
POST http://localhost:3000/add-users
Content-Type: application/json

{
    "name": "Rio",
    "email": "aryamuktisatria@gmail.com",
    "password": "iniPassSaya2",
    "noHP": "00123220198",
    "role": "user"
}

###
POST http://localhost:3000/add-users
Content-Type: application/json

{
  "name": "Admin",
  "email": "admin1@gmail.com",
  "password": "admin1234",
  "noHP": "08123456789",
  "role": "admin"
}

###
POST http://localhost:3000/add-users
Content-Type: application/json

{
   "name": "RIOOOO",
    "email": "rio123@gmail.com",
    "password": "Riooke2004_",
    "noHP": "00123220198",
    "role": "user"
}

// Ini Terbaru
###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "RyanKanaNyola",
  "email": "ryankny@gmail.com",
  "password": "123220198",
  "confirmPassword": "123220198",
  "noHP": "081234567890",
  "role": "admin"
}

###
POST https://laundry-198-325333151890.us-central1.run.app/api/users/register
Content-Type: application/json

{
  "name": "Contoh Register",
  "email": "contoh@gmail.com",
  "password": "contoh123220198",
  "confirmPassword": "contoh123220198",
  "noHP": "081234567890",
  "role": "admin"
}

###
POST https://laundry-198-325333151890.us-central1.run.app/api/users/login
Content-Type: application/json

{
    "email": "contoh@gmail.com",
    "password": "contoh123220198"
}

###
POST http://localhost:3000/api/users/register
Content-Type: application/json

{
  "name": "RyanKNy",
  "email": "rkn@gmail.com",
  "password": "123220198",
  "confirmPassword": "123220198",
  "noHP": "081234567890"
}

###
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "user_id": 8,
  "weight": 3.5,
  "service_type": "Express",
  "total_price": 150000,
  "status": "Pending",
  "isPaid": false
}

###
POST http://localhost:3000/api/payments
Content-Type: application/json

{
  "order_id": 6,
  "method": "Credit Card",
  "amount": 150000,
  "status": true
}

###
POST http://localhost:3000/api/payments
Content-Type: application/json

{
  "order_id": 6,
  "method": "Tunai",
  "amount": 150000,
  "status": true
}

###
POST https://laundry-198-325333151890.us-central1.run.app/api/users/login
Content-Type: application/json

{
    "email": "123220198@student.upnyk.ac.id",
    "password": "12345678"
}

###
GET https://laundry-198-325333151890.us-central1.run.app/api/orders

###
PUT http://localhost:3000/api/users/8
Content-Type: application/json

{
  "password": "ryankny198"
}

###
GET http://localhost:3000/api/users/12

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "user26@gmail.com",
    "password": "qwerty12"
}


###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "ayudya@gmail.com",
    "password": "rkn123220198"
}

###
GET https://laundry-198-325333151890.us-central1.run.app/api/users